# Generated by Django 2.0.2 on 2018-08-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
