# Generated by Django 2.0.2 on 2018-08-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multiconf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(default='null', max_length=500)),
                ('confConfigFileNames', models.CharField(default='null', max_length=500)),
                ('txtConfigFileNames', models.CharField(default='null', max_length=500)),
            ],
        ),
    ]
