INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (1, '计算机网络', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (2, '人工智能', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (3, '计算机软件', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (4, '智能', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (5, '计算机科学理论', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (6, '数据库学术', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (7, '移动医疗', 6);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (8, '多媒体技术', 45);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (9, '通信技术', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (10, '网络安全', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (11, '信息安全', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (15, '计算机系统结构', 18);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (16, '计算机系统结构与硬件', 18);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (18, '计算机应用技术', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (19, '电子工程', 32);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (20, '电子', 32);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (21, '智能系统', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (22, '图像处理', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (23, '信号与图像处理', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (24, '游戏制作', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (25, '交互', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (26, '应用数学', 20);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (27, '通信', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (28, '信号分析', 21);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (29, '物联网', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (30, '物联网安全', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (31, '大数据', 15);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (32, '网络', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (33, '传感器', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (34, '通讯', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (35, '教育学', 7);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (36, 'Data Mining Techniques', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (37, '车载技术', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (38, '无线移动通信', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (39, '计算机安全', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (40, '生物信号处理', 21);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (41, '安全', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (42, '自然语言处理', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (43, '信息系统', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (44, '通信与网络', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (45, '信息共享', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (46, '高性能', 18);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (47, '无线通信', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (48, '自动', 17);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (49, 'Pattern Recognition', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (50, '自动化', 17);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (51, '自动化控制', 17);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (54, '大数据与自然语言处理', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (55, '图像与视频', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (56, '图像', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (57, '视频', 45);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (58, '图像技术', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (59, '视频技术', 45);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (60, 'Computer Security', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (61, '智能计算', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (62, '模式识别', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (63, '机器智能', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (64, '机器学习', 33);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (65, '计算语言学', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (66, '图形学', 45);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (67, '计算机辅助设计', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (68, 'distributed computing ', 22);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (69, '计算机视觉', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (70, '人机交互', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (71, '数据统计', 20);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (72, '绘图', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (73, '软件工程', 42);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (74, '科研绘图', 24);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (75, '科研', 24);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (76, '云计算', 13);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (77, '机器人', 25);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (78, '控制技术', 17);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (79, '数据分析', 20);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (80, '基因组科学', 11);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (81, '信号处理', 21);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (82, '统计软件', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (83, '计算机管理', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (84, '医疗', 11);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (85, '医疗与健康信息学', 11);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (86, '医疗与健康', 11);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (87, '科研论文', 24);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (88, '交通工程', 26);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (89, '运输系统', 26);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (90, '信息科学', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (91, '交通运输', 26);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (92, '计算机技术', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (93, '信息管理', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (94, '计算机与通信', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (95, '图形与图像处理', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (96, '互联网与电子商务', 27);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (97, '电子商务', 27);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (98, '商务工程', 27);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (99, '电子技术', 17);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (100, '机械系统', 17);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (101, '金融科技', 28);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (102, '数字图像处理', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (103, '生物医学', 11);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (104, '云计算与大数据', 13);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (105, '网络协议', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (106, '服务工程', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (109, '智能制造', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (110, '智能制造技术', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (111, '图像与图形处理', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (112, '生物信息学', 11);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (113, '计算机生物', 11);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (114, '虚拟现实', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (115, '加密', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (116, '隐私', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (117, '计算机图形', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (118, '机器视觉', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (119, '数字信号处理', 21);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (120, '数字信号', 21);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (121, '信息技术', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (122, '生物医学工程', 11);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (123, '智能控制', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (124, '航空航天工程', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (125, '电力系统', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (126, '导航', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (127, '通信系统', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (128, '教育', 7);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (129, '生物技术', 11);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (130, '医药科学', 11);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (131, '计算机建模', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (132, '仿真', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (133, '遥感技术', 30);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (134, '遥感', 30);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (135, '遥感技术与应用', 30);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (136, '集成电路', 18);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (137, '智能农业', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (138, '微系统', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (139, '模糊系统', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (140, '数据挖掘', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (141, '智能城市', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (142, '信号采集', 21);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (143, '信号采集与处理', 21);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (144, '环境科学', 31);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (145, '光电探测技术', 31);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (146, '分子影像', 31);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (147, '机械电气工程', 31);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (148, '无人机', 25);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (149, '无人机系统', 25);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (150, '高性能计算', 40);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (151, '深度学习', 9);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (152, '统计学', 20);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (153, '智能信息处理', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (154, '科研论文绘图', 24);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (155, '供应链', 26);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (156, '物流', 26);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (157, '智能自动化系统', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (158, '数据科学', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (159, '风险评估', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (160, '漏洞分析', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (161, '分布式', 22);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (162, '分布式网络', 22);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (163, '挖掘', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (164, '软件挖掘', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (165, '商业智能', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (166, '软件安全', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (167, '软件容错', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (168, '电子学', 32);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (169, '计算机', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (170, 'version control', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (171, '工业控制系统', 17);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (172, '语言动力系统', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (173, '情感', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (174, '智力', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (175, '数据处理', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (176, '情感计算', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (177, '智能互动', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (178, '算法', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (179, '触觉', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (180, '软件认证', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (181, '多核系统', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (182, '情感分析', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (183, 'Recognition', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (184, '感知', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (185, '手势', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (186, '视觉', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (187, '视听媒体', 45);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (188, '生物图像', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (189, 'Computer Vision', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (190, '自动驾驶', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (191, '聊天机器人', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (192, '自然语言理解', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (193, '自动问答', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (194, '视觉监测', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (195, '重建语义学', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (196, '智能软件', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (197, '文本处理', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (198, 'Information Resources Management', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (199, '移动通信', 6);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (200, '游戏数据科学', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (201, '游戏', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (202, '数字信息', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (203, 'Nuclear', 31);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (204, 'Intelligence ', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (205, 'Hardware Oriented Security', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (207, '可视化', 20);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (208, '数据库', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (209, '嵌入式系统', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (210, '嵌入式', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (211, 'Security in Networking', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (212, '智能设备', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (213, '芯片', 18);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (214, '芯片架构', 18);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (215, '网络芯片架构', 18);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (216, '信息网络', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (217, 'Intelligent Transportation Systems', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (218, 'Intelligent Transportation', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (219, 'Embedded ', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (220, '多媒体信号处理', 45);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (221, '并行编程', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (222, '系统建模', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (223, '神经网络', 9);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (224, 'ACM', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (225, '视觉语言', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (226, '智能化', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (227, '架构', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (228, '业务', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (229, 'VR', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (230, 'AR', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (231, '无线安全', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (232, 'Network', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (233, 'Enterprise', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (235, '增强现实', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (236, '安全隐私', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (237, '智慧', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (238, '交互式', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (239, '交互式分析', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (240, '系统', 43);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (242, 'Data Mining', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (243, '数据工程', 20);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (244, 'Robotics', 25);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (245, '云存储', 41);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (246, '云存储服务', 41);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (247, '视频图像处理', 45);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (248, 'Computer Graphics', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (249, 'Visualization', 20);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (251, '信息化', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (252, 'Intelligent Data Engineering ', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (253, 'Intelligent Data', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (254, 'Automated', 17);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (255, '软件与应用', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (256, '模糊集', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (257, '粗糙集', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (258, '理论', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (259, '性能评估', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (260, '培训', 7);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (261, '移动监控', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (262, '医疗服务', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (263, 'Computer Application', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (264, 'Architecture of Computing Systems', 18);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (265, 'Intelligent Systems ', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (266, 'Dialog System ', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (267, 'Software Technologies', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (268, 'Big Data', 15);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (269, 'Software', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (270, 'Artificial Intelligence', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (271, 'Cloud Computing', 13);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (272, 'Enterprise Information System', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (273, 'Information System', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (274, 'Communication', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (275, 'Multimedia ', 45);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (277, 'Intelligent', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (278, 'Electronics', 32);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (279, 'Database System', 34);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (280, 'Computing Systems and Applications', 35);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (281, 'Computing System', 35);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (282, 'Parallel Programming', 35);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (283, 'IoT ', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (284, 'AUTOMATA THEORY', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (285, 'Theory', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (286, 'Intelligent System', 36);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (290, 'Information Technology', 37);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (291, 'Architectures', 18);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (292, 'Computational Science', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (293, 'Wireless Security', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (294, 'Security', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (295, 'Safety', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (296, 'Automation ', 17);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (297, 'Object-oriented Programming', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (298, 'OOP', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (299, 'Internet of Things', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (300, 'programming', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (301, 'Data Analytics', 20);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (303, 'Distributed', 22);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (304, 'Biomedical Engineering', 38);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (305, 'Mathematical Programming', 31);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (306, 'CyberSecurity and Privacy', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (307, 'CyberSecurity', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (308, 'Privacy', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (309, 'Data Compression', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (310, 'REAL-TIME COMPUTING', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (311, 'COMPUTING', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (312, 'Decision Support Systems', 9);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (313, 'Compiler ', 5);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (314, 'Computer Science', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (315, 'Big-data', 15);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (316, 'Intelligent Computing', 36);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (317, 'Information Extraction', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (318, 'Semantic', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (319, 'AI', 1);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (320, 'Parallel', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (321, 'Computing Systems', 35);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (322, 'Deep Learning', 9);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (323, 'Communicates', 14);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (324, 'Electronic and Automation Control', 17);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (325, 'Automation Control', 17);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (326, 'Informatics', 37);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (327, 'Mining ', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (328, 'Information Technologies', 37);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (329, 'Cyber', 4);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (330, 'Reasoning ', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (331, 'Medicine', 38);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (332, 'Biology ', 38);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (334, 'Technology Enhanced Learning', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (336, 'Computer Engineering', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (337, 'Electrical Technologies', 32);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (338, 'Information Science', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (339, 'INFORMATION SECURITY ', 2);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (341, 'Image Computing', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (342, 'Wearable', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (343, 'Human Computer Interaction', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (344, 'Interaction', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (345, 'Computer-Human Interaction', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (346, 'Sensor', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (347, 'Sensing', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (348, 'Signal Processing ', 21);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (349, 'Picture Coding', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (350, 'Picture', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (351, 'Smart Device', 25);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (352, 'Sensing System', 3);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (353, 'Digital Economy', 35);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (354, 'Computing Algorithm', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (355, 'Database Management', 34);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (356, 'Fuzzy System', 36);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (357, 'Interactive System', 23);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (358, 'Wireless', 4);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (359, 'Machine Learning', 33);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (360, 'Computational Linguistic', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (361, 'Document Analysis', 8);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (362, 'Machine Vision', 39);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (364, 'Robot', 25);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (365, 'Data Analysis of Images', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (366, 'Image Processing', 10);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (367, 'Web Service', 35);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (369, 'Distributed Computing System', 22);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (370, 'DIGITAL SIGNAL PROCESSING', 35);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (371, 'User Interface', 35);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (372, 'High Performance', 35);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (373, 'Mobile Service', 35);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (374, 'Automata', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (375, 'Web Technology', 4);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (376, 'Robot Vision', 39);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (377, 'Cluster Computing', 35);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (378, 'Large Database', 34);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (379, 'Programming Language', 19);
INSERT INTO `Tags` (`id`, `name`, `directionId`) VALUES (381, 'Automatic Control', 17);
