# Generated by Django 2.0.2 on 2018-07-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_url', models.CharField(default='null', max_length=500)),
                ('website_select', models.CharField(default='null', max_length=500)),
                ('website_reg', models.CharField(default='null', max_length=500)),
                ('cnName_select', models.CharField(default='null', max_length=500)),
                ('cnName_reg', models.CharField(default='null', max_length=500)),
                ('enName_select', models.CharField(default='null', max_length=500)),
                ('enName_reg', models.CharField(default='null', max_length=500)),
                ('introduce_select', models.CharField(default='null', max_length=3000)),
                ('introduce_reg', models.CharField(default='null', max_length=3000)),
                ('location_select', models.CharField(default='null', max_length=500)),
                ('location_reg', models.CharField(default='null', max_length=500)),
                ('sponsor_select', models.CharField(default='null', max_length=500)),
                ('sponsor_reg', models.CharField(default='null', max_length=500)),
                ('startdate_select', models.CharField(default='null', max_length=500)),
                ('startdate_reg', models.CharField(default='null', max_length=500)),
                ('enddate_select', models.CharField(default='null', max_length=500)),
                ('enddate_reg', models.CharField(default='null', max_length=500)),
                ('deadline_select', models.CharField(default='null', max_length=500)),
                ('deadline_reg', models.CharField(default='null', max_length=500)),
                ('image_select', models.CharField(default='null', max_length=500)),
                ('image_reg', models.CharField(default='null', max_length=500)),
                ('tag_select', models.CharField(default='null', max_length=500)),
                ('tag_reg', models.CharField(default='null', max_length=500)),
                ('pub_time', models.DateField(null=True)),
                ('level', models.CharField(blank=True, choices=[('普通', '普通'), ('紧急', '紧急')], max_length=5, null=True)),
            ],
        ),
    ]
